controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controller:
  ros__parameters:
    joints:
      - l_ab_ad
      - l_yaw
      - l_upper
      - l_lower
      - l_foot
      - r_ab_ad
      - r_yaw
      - r_upper
      - r_lower
      - r_foot

    command_interfaces:
      - effort
      
    state_interfaces:
      - position
      - velocity
      - effort